### ISSUE TITLE
CRITICAL VULNERABILITY: USER USES PYTHON

### ISSUE THREAD

**Issue by CreeperMann** [scratchsay/scratchsay#1]
The severity of this vulnerability should not be understated. The vulnerability could cause the programmer to be stuck in USACO bronze. This could also cause the user to get familiar with using indents instead of using braces, which is punishable by death. Even worse, the programmer could stop using semicolons, which is *the* founding principle of programming. I suggest this be fixed immediately and instead the programmer use the languages Richard Stallman intended, such as C++ or C. However, using javascript is a way to resolve this issue, but is strongly recommended against, as javascript goes against the design pattern of programming languages to be usable.

**Comment by scratchsay** [comment]
I understand your concerns, however these concerns contain exaggerations and lies rather than valid arguments. If you would like we can have a chat about the potential vulnerabilities of Python.
